import { Constants } from "@modules"
export const constants: Constants = {
    items: [
        "📻 Spirit box",
        "📖 Book",
        "📸 Photo Camera",
        "🚥 EMF",
        "📹 Video Camera",
        "😎 UV Flashlight",
        "🟢 D.O.T.S.",
        "🕯️ Candle",
        "✝️ Crucifix",
        "🍆 Glow Stick",
        "📷 Head Mounted Camera",
        "🏃 Motion Sensor",
        "🔥 Lighter",
        "📡 Parabolic Mic",
        "🧂 Salt",
        "💊 Pills",
        "☁️ Smudge Stick",
        "🎵 Sound Sensor",
        "🔦 Strong Flashlight",
        "🌡️ Thermometer",
        "🔭 Tripod"
    ],

    inviteLink: "https://discord.com/api/oauth2/authorize?client_id=887086717587320852&scope=applications.commands",
    supportInviteLink: "https://discord.gg/4eJsE2byEY",
    maps: ["Tanglewood", "Edgefield", "Willow", "Ridgeview", "Grafton", "Bleasdale", "Highschool", "Prison", "Asylum", "Campfire"],
    clueNames: [
        "🚥 EMF 5",
        "📖 Ghost Writing",
        "🖐️ Fingerprints",
        "📻 Spiritbox",
        "✨ Ghost orbs",
        "❄️ Freezing",
        "🟢 D.O.T.S."
    ],
    ghosts: new Map<string, number[]>([
        ["Myling", [0, 1, 2]],
        ["Spirit", [0, 1, 3]],
        ["Shade", [0, 1, 5]],
        ["Obake", [0, 2, 4]],
        ["Jinn", [0, 2, 5]],
        ["Goryo", [0, 2, 6]],
        ["The Twins", [0, 3, 5]],
        ["Wraith", [0, 3, 6]],
        ["Raiju", [0, 4, 6]],
        ["Oni", [0, 5, 6]],
        ["Poltergeist", [1, 2, 4]],
        ["Demon", [1, 2, 5]],
        ["Mare", [1, 3, 4]],
        ["Revenant", [1, 4, 5]],
        ["Phantom", [2, 3, 6]],
        ["Hantu", [2, 4, 5]],
        ["Banshee", [2, 4, 6]],
        ["Onryo", [3, 4, 5]],
        ["Yokai", [3, 4, 6]],
        ["Yurei", [4, 5, 6]],
    ]),
};
